version: '3'
services:
  virtual-vehicle-utility:
    image: bringauto/virtual-vehicle-utility:v3.1.2
    profiles: ["all", "without-module-gateway", "without-external-server", "core", "virtual-vehicle-utility"]
    volumes:
      - ./docker_volumes/virtual-vehicle-utility:/virtual-vehicle-utility/log
      - ./configuration/virtual-vehicle-utility:/virtual-vehicle-utility/config
    entrypoint: ["/virtual-vehicle-utility/bin/virtual-vehicle-utility",
                 "--config=/virtual-vehicle-utility/config/config.json"]
    restart: "no"
    networks:
      - bring-emulator

  virtual-plc:
    image: bringauto/virtual-plc:v1.0.0
    profiles: ["all", "without-module-gateway", "without-external-server", "core", "virtual-plc"]
    volumes:
      - ./docker_volumes/virtual-plc:/home/bringauto/virtual-plc/log
      - ./configuration/virtual-plc:/home/bringauto/virtual-plc/config
    entrypoint: ["/home/bringauto/virtual-plc/bin/virtual_plc",
                 "--config=/home/bringauto/virtual-plc/config/config.json"]
    restart: "no"
    networks:
      - bring-emulator

  module-gateway:
    image:  bringauto/module-gateway:v1.1.2
    profiles: ["all", "without-devices", "without-external-server", "module-gateway", "core"]
    volumes:
      - ./docker_volumes/module-gateway:/home/bringauto/log/
      - ./configuration/module-gateway:/home/bringauto/config/
    ports:
      - 1636:1636
    entrypoint: ["/home/bringauto/module-gateway/bin/module-gateway-app",
                 "--config-path=/home/bringauto/config/config.json",
                 "--verbose"]
    restart: "no"
    networks:
      - bring-emulator

  vernemq:
    image: bringauto/vernemq:1.13.0
    profiles: ["all", "without-devices", "without-module-gateway", "without-external-server", "mqtt"]
    volumes:
      - ./docker_volumes/vernemq:/vernemq/log/log/
      - ./configuration/vernemq:/etc/vernemq/
    ports:
      - 1883:1883
      - 8883:8883
    restart: "no"
    networks:
      - bring-emulator

  external-server:
    image: bringauto/external-server:v1.1.4
    profiles: ["all", "without-devices", "without-module-gateway", "without-external-server"]
    volumes:
      - ./docker_volumes/external-server:/home/bringauto/log
      - ./configuration/external-server:/home/bringauto/config/
    entrypoint: ["python3",
                 "/home/bringauto/external_server/external_server_main.py",
                 "--config=/home/bringauto/config/config.json" ]
    restart: "no"
    networks:
      - bring-emulator

  http-api:
    image: bringauto/fleet-protocol-http-api:v2.3.1
    profiles: ["all", "without-devices", "without-module-gateway", "http-api"]
    ports:
      - 8080:8080
    restart: on-failure:10
    depends_on:
      - postgresql-database
    networks:
      - bring-emulator
    volumes:
      - ./configuration/http-api/config.json:/usr/src/app/config.json
    entrypoint:
      ["python3", "-m", "server",
       "config.json",
       "--location=postgresql-database"]

  postgresql-database:
    image: postgres:16
    profiles: ["all", "without-devices", "without-module-gateway", "http-api"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    restart: "no"
    networks:
      - bring-emulator
    ports:
      - 5432:5432
    volumes:
      - ./db/insert_test_api_key.sql:/docker-entrypoint-initdb.d/insert_test_api_key.sql

networks:
  bring-emulator:
    name: bring-emulator
