version: '3'
services:
  mosquitto:
    image: bringauto/mosquitto:v1.1.0
    profiles: ["all", "without-fleet", "without-autonomy", "without-daemon", "mosquitto", "core"]
    volumes:
      - ./docker_volumes/mosquitto/log:/mosquitto/log
      - ./docker_volumes/mosquitto/data:/mosquitto/data
      - ./configuration/mosquitto:/mosquitto/config/
    ports:
      - 1883:1883
      - 8883:8883
    restart: always
    networks:
      - bring-emulator

  virtual-fleet:
    image:  bringauto/virtual-fleet:v2.2.0
    profiles: ["all", "without-autonomy", "without-broker", "without-daemon"]
    volumes:
      - ./docker_volumes/virtual-fleet:/virtual-fleet/log
    entrypoint: ["/virtual-fleet/virtual-fleet-app",
                 "--broker-ip=mosquitto",
                 "--broker-port=1883",
                 "--log-path=/virtual-fleet/log/"]
    restart: always
    networks:
      - bring-emulator

  bringauto-daemon:
    image:  bringauto/bringauto-daemon:v1.5.0
    profiles: ["all", "without-fleet", "without-autonomy", "without-broker", "core", "car"]
    volumes:
      - ./docker_volumes/bringauto-daemon:/bringauto-daemon/log
      - ./configuration/daemon:/certificates/
    ports:
      - 1636:1636
    entrypoint: ["/bringauto-daemon/_build/components/industrial_portal/industrial_portal",
                 "--mode=mqtt",
                 "--company=${COMPANY:-bringauto}",
                 "--place=${PLACE:-default}",
                 "--vehicle-name=${VEHICLE_NAME:-BringAuto Virtual}",
                 "--broker-ip=mosquitto",
                 "--broker-port=1883",
                 "--mqtt-ssl=false",
                 "--ca-file=/certificates/ca-chain.pem",
                 "--client-cert=/certificates/client.pem",
                 "--client-key=/certificates/client.key",
                 "--port=1636",
                 "--log-path=/bringauto-daemon/log/"]
    restart: always
    networks:
      - bring-emulator

  virtual-vehicle-utility:
    image: bringauto/virtual-vehicle-utility:v2.4.0
    profiles: ["all", "without-fleet", "without-broker", "without-daemon", "car"]
    volumes:
      - ./docker_volumes/virtual-vehicle-utility:/virtual-vehicle-utility/log
    entrypoint: ["/virtual-vehicle-utility/virtual-vehicle-utility",
                 "--map=/virtual-vehicle-utility/maps/Brno.osm",
                 "--verbose",
                 "--daemon-ip=bringauto-daemon",
                 "--daemon-port=1636",
                 "--wait=30",
                 "--log-path=/virtual-vehicle-utility/log/",
                 "--period=1000",
                 "--vehicle-provider=simulation"]
    restart: always
    networks:
      - bring-emulator

networks:
  bring-emulator:
    name: bring-emulator
